Repository Team-kiwing/Team-3seco-kiwing-fe, pull requests merged in 2024-02, with the labels that each got.

#3 [#1] 프로젝트 세팅
  index.html
  package.json
  public/kiwing_circle_009c4d.png
  public/kiwing_circle_green.png
  public/kiwing_circle_white.png
  public/kiwing_square_green.png
  public/kiwing_square_white.png
  public/mockServiceWorker.js
  src/App.tsx
  src/assets/asset.md
  src/components/common/index.ts
  src/components/index.tsx
  src/constants/index.ts
  src/hooks/index.ts
  src/main.tsx
  src/mock/browser.ts
  src/mock/dummy.json
  src/mock/handlers.ts
  src/pages/AuthPage/index.tsx
  src/pages/HubPage/index.tsx
  src/pages/MainPage/index.tsx
  src/pages/MyListPage/index.tsx
  src/pages/NotFoundPage/index.tsx
  src/pages/RegisterPage/index.tsx
  src/pages/ReportPage/index.tsx
  src/pages/SharedItemPage/index.tsx
  src/pages/SharedPage/index.tsx
  src/pages/TestPage/index.tsx
  src/routes/index.tsx
  src/stores/index.ts
  src/styles/globalStyles.ts
  src/styles/theme.ts
  src/styles/uiContext.tsx
  src/types/index.ts
  src/utils/localStorage.ts
  tsconfig.json
  vite.config.ts
Labels: 기능, 세팅

#7 [#6] 프로젝트 세팅 v1.0.1
  src/App.tsx
  src/main.tsx
  src/pages/AuthPage/index.tsx
  src/pages/HubPage/index.tsx
  src/pages/MainPage/index.tsx
  src/pages/MyListPage/index.tsx
  src/pages/NotFoundPage/index.tsx
  src/pages/RegisterPage/index.tsx
  src/pages/ReportPage/index.tsx
  src/pages/SharedItemPage/index.tsx
  src/pages/SharedPage/index.tsx
  src/pages/TestPage/index.tsx
  src/pages/index.ts
  src/routes/index.tsx
Labels: 버그, 픽스, 기능, 세팅

#27 [#26] 프로젝트 세팅 v1.1.0
  src/constants/index.ts
  src/main.tsx
  src/styles/theme.ts
Labels: 디자인, 기능, 세팅

#12 [#10] AES 암,복호화 코드 v1.0.0
  src/utils/crypto.ts
Labels: 기능

#17 [#16] 프로젝트 readme v1.0.0
  README.md
Labels: 세팅

#24 [#5] Avatar 컴포넌트 v1.0.0
  src/assets/profile.png
  src/components/common/Avatar/Avatar.const.ts
  src/components/common/Avatar/Avatar.style.ts
  src/components/common/Avatar/Avatar.tsx
  src/components/common/Avatar/Avatar.type.ts
  src/components/common/Avatar/index.ts
Labels: 디자인, 기능

#20 [#19] ImageUpload 컴포넌트 v1.0.0
  src/components/common/ImageUpload/ImageUpload.style.ts
  src/components/common/ImageUpload/ImageUpload.tsx
  src/components/common/ImageUpload/ImageUpload.type.ts
  src/components/common/ImageUpload/index.tsx
Labels: 디자인, 기능

#25 [#8] ShadowBox 컴포넌트 v1.0.0
  src/components/common/ShadowBox/ShadowBox.style.ts
  src/components/common/ShadowBox/ShadowBox.tsx
  src/components/common/ShadowBox/ShadowBox.type.ts
  src/components/common/ShadowBox/index.ts
Labels: 디자인, 기능

#33 [#32] Avatar 컴포넌트 v1.0.1
  src/components/common/Avatar/Avatar.style.ts
Labels: 디자인, 리팩토링

#36 [#35] ShadowBox 컴포넌트 v1.0.1
  src/components/common/ShadowBox/ShadowBox.style.ts
  src/components/common/ShadowBox/ShadowBox.tsx
  src/components/common/ShadowBox/ShadowBox.type.ts
Labels: 디자인, 리팩토링

#18 [#11] Badge 컴포넌트 v1.0.0
  src/components/common/Badge/Badge.style.ts
  src/components/common/Badge/Badge.tsx
  src/components/common/Badge/Badge.type.ts
  src/components/common/Badge/index.tsx
Labels: 디자인, 기능

#14 [#13] 아이콘 래핑 컴포넌트 v1.0.0
  .eslintrc.cjs
  .husky/pre-commit
  .husky/pre-push
  src/components/common/IconWrapper/IconWrapper.tsx
  src/components/common/IconWrapper/index.ts
Labels: 디자인, 기능

#21 [#15] 웹 네비게이션 바 컴포넌트 v1.0.0
  public/kiwing_circle_transparent.png
  public/kiwing_logos_transparent_fit_square.png
  public/kiwing_onlywing_logos_transparent.png
  public/kiwing_onlywing_logos_transparent_fit.png
  src/components/common/Navigator/WebNavBar/WebNavBar.hook.ts
  src/components/common/Navigator/WebNavBar/WebNavBar.style.tsx
  src/components/common/Navigator/WebNavBar/WebNavBar.tsx
  src/components/common/Navigator/WebNavBar/index.ts
  src/constants/router.ts
Labels: 디자인, 기능

#37 [#22] 모바일 하단 내비게이션 바 v1.0.0
  src/components/common/IconWrapper/IconWrapper.tsx
  src/components/common/Navigator/MobileBottomNavBar/MobileBottomNavBar.hook.ts
  src/components/common/Navigator/MobileBottomNavBar/MobileBottomNavBar.style.ts
  src/components/common/Navigator/MobileBottomNavBar/MobileBottomNavBar.tsx
  src/components/common/Navigator/MobileBottomNavBar/index.ts
  src/components/common/Navigator/WebNavBar/WebNavBar.style.tsx
Labels: 디자인, 기능

#47 [#46] Avatar 컴포넌트 jsDoc 수정 v1.0.2
  src/components/common/Avatar/Avatar.tsx
Labels: 리팩토링

#45 [#29] Input 컴포넌트 구현 v1.0.0
  src/components/common/Input/Input.style.ts
  src/components/common/Input/Input.tsx
  src/components/common/Input/Input.type.ts
  src/components/common/Input/index.ts
  src/styles/theme.ts
Labels: 디자인, 기능

#53 [#52] Badge 컴포넌트 구현 v1.1.0
  src/components/common/Badge/Badge.style.ts
  src/components/common/Badge/Badge.tsx
  src/components/common/Badge/Badge.type.ts
  src/styles/theme.ts
Labels: 디자인, 기능

#61 [#60] 프로젝트 세팅 v1.1.1
  src/constants/index.ts
  src/constants/router.ts
  src/routes/index.tsx
  src/styles/globalStyles.ts
Labels: 디자인, 기능, 논의

#54 [#30] Textarea 컴포넌트 구현 v1.0.0
  src/components/common/Textarea/Textarea.style.ts
  src/components/common/Textarea/Textarea.tsx
  src/components/common/Textarea/Textarea.type.ts
  src/components/common/Textarea/index.ts
Labels: 디자인, 기능

#59 [#58] Input 컴포넌트 v1.0.1
  src/components/common/Input/Input.style.ts
  src/components/common/Input/Input.tsx
Labels: 리팩토링

#48 [#38] Button(사각형) 컴포넌트 구현 v1.0.0
  src/components/common/Button/Button.style.ts
  src/components/common/Button/Button.tsx
  src/components/common/Button/Button.type.ts
  src/components/common/Button/index.ts
Labels: 디자인, 기능

#49 [#39] Button(원형) 컴포넌트 구현 v1.0.0
  src/components/common/CircleButton/CircleButton.style.ts
  src/components/common/CircleButton/CircleButton.tsx
  src/components/common/CircleButton/CircleButton.type.ts
  src/components/common/CircleButton/index.ts
Labels: 디자인, 기능

#50 [#41] 모바일 상단 내비게이션 바 v1.0.0
  src/components/common/Navigator/MobileBottomNavBar/MobileBottomNavBar.tsx
  src/components/common/Navigator/MobileTopNavBar/MobileTopNavBar.style.ts
  src/components/common/Navigator/MobileTopNavBar/MobileTopNavBar.tsx
  src/components/common/Navigator/MobileTopNavBar/index.ts
Labels: 디자인, 기능

#56 [#55] Selector 컴포넌트 구현 v1.0.0
  src/components/common/Selector/Selector.style.ts
  src/components/common/Selector/Selector.tsx
  src/components/common/Selector/Selector.type.ts
  src/components/common/Selector/index.tsx
Labels: 디자인, 기능

#73 [#72] ShadowBox v1.1.0
  src/components/MyListDropDown/MyListDropDown.tsx
  src/components/MyListDropDown/index.ts
  src/components/common/ShadowBox/ShadowBox.tsx
  src/components/common/Toggle/Toggle.hook.ts
  src/components/common/Toggle/Toggle.style.ts
  src/components/common/Toggle/Toggle.tsx
  src/components/common/Toggle/Toggle.type.ts
  src/components/common/Toggle/index.ts
Labels: 기능, 리팩토링

#79 [#78] Toggle, MyListDropDown 테스트 코드 삭제
  src/components/MyListDropDown/MyListDropDown.tsx
  src/components/MyListDropDown/index.ts
  src/components/common/Toggle/Toggle.hook.ts
  src/components/common/Toggle/Toggle.style.ts
  src/components/common/Toggle/Toggle.tsx
  src/components/common/Toggle/Toggle.type.ts
  src/components/common/Toggle/index.ts
Labels: 리팩토링

#51 [#44] TagFilter 컴포넌트 구현 v1.0.0
  src/components/common/TagFilter/TagFilter.style.tsx
  src/components/common/TagFilter/TagFilter.tsx
  src/components/common/TagFilter/TagFilter.type.ts
  src/components/common/TagFilter/index.tsx
Labels: 디자인, 기능

#81 [#80] 프로젝트 세팅 v1.1.2
  src/constants/router.ts
  src/pages/PolicyPage/Policy.tsx
  src/pages/PolicyPage/index.tsx
  src/pages/index.ts
  src/routes/index.tsx
  src/styles/theme.ts
Labels: 디자인, 기능

#71 [#40] DropDown 컴포넌트 구현 v1.0.0
  src/components/common/Button/Button.tsx
  src/components/common/DropDown/DropDown.hook.ts
  src/components/common/DropDown/DropDown.style.ts
  src/components/common/DropDown/DropDown.tsx
  src/components/common/DropDown/DropDown.type.ts
  src/components/common/DropDown/index.ts
  src/styles/globalStyles.ts
Labels: 디자인, 기능

#87 [#85] DropDown v1.0.1
  src/components/common/DropDown/DropDown.tsx
Labels: 디자인, 리팩토링

#66 [#42] 전역 상태 모달 v1.0.0
  src/components/common/ModalLayout/ModalLayout.style.ts
  src/components/common/ModalLayout/ModalLayout.tsx
  src/components/common/ModalLayout/index.ts
  src/hooks/useModal.tsx
  src/hooks/useResize.tsx
  src/routes/index.tsx
  src/stores/index.ts
  src/utils/bodyScrollLock.ts
  src/utils/isMobile.ts
Labels: 디자인, 기능

#70 [#68] 404 페이지 v1.0.0
  src/components/common/EasterEgg/EasterEgg.style.ts
  src/components/common/EasterEgg/EasterEgg.tsx
  src/components/common/EasterEgg/index.ts
  src/pages/NotFoundPage/NotFound.style.ts
  src/pages/NotFoundPage/NotFound.tsx
  src/pages/NotFoundPage/index.tsx
Labels: 디자인, 기능

#77 [#76] Toggle 컴포넌트 구현 v1.0.0
  src/components/common/Toggle/Toggle.style.ts
  src/components/common/Toggle/Toggle.tsx
  src/components/common/Toggle/Toggle.type.ts
  src/components/common/Toggle/index.ts
Labels: 디자인, 기능

#82 [#63] Badge 컴포넌트 구현 v1.2.0
  src/components/common/Badge/Badge.style.ts
  src/components/common/Badge/Badge.tsx
  src/components/common/Badge/Badge.type.ts
  src/styles/theme.ts
Labels: 디자인, 기능, 리팩토링

#103 [#102] 프로젝트 세팅 v1.1.3
  src/constants/index.ts
  src/styles/globalStyles.ts
  src/styles/theme.ts
Labels: 디자인, 리팩토링

#62 [#57] 검색바 컴포넌트 구현 v1.0.0
  src/components/common/SearchBar/SearchBar.style.ts
  src/components/common/SearchBar/SearchBar.tsx
  src/components/common/SearchBar/SearchBar.type.ts
  src/components/common/SearchBar/index.ts
Labels: 디자인, 기능

#75 [#28] UserInfoCard 컴포넌트 구현 v1.0.0
  src/components/common/UserInfoCard/UserInfoCard.style.ts
  src/components/common/UserInfoCard/UserInfoCard.tsx
  src/components/common/UserInfoCard/UserInfoCard.type.ts
  src/components/common/UserInfoCard/index.ts
Labels: 디자인, 기능

#74 [#64] BundleCard 컴포넌트 구현 1.0.0
  src/components/common/BundleCard/BundleCard.style.ts
  src/components/common/BundleCard/BundleCard.tsx
  src/components/common/BundleCard/BundleCard.type.ts
  src/components/common/BundleCard/index.tsx
Labels: 디자인, 기능

#84 [#83] SharedBundleCard 컴포넌트 구현 v1.0.0
  src/components/SharedBundleCard/SharedBundleCard.style.ts
  src/components/SharedBundleCard/SharedBundleCard.tsx
  src/components/SharedBundleCard/SharedBundleCard.type.ts
  src/components/SharedBundleCard/index.ts
Labels: 디자인, 기능

#109 [#107] Button(사각형) v1.0.1
  src/components/common/Button/Button.style.ts
  src/components/common/Button/Button.tsx
  src/components/common/Button/Button.type.ts
Labels: 디자인, 리팩토링

#106 [#105] Toggle v1.1.0
  src/components/common/Toggle/Toggle.style.ts
  src/components/common/Toggle/Toggle.tsx
  src/components/common/Toggle/Toggle.type.ts
Labels: 디자인, 기능

#91 [#89] SharedBundleDropDown 컴포넌트 구현 v1.0.0
  src/components/BundleDropDown/BundleDropDown.style.ts
  src/components/BundleDropDown/BundleDropDown.tsx
  src/components/BundleDropDown/BundleDropDown.type.ts
  src/components/BundleDropDown/index.ts
  src/components/SharedBundlePage/SharedBundleDropDown/SharedBundleDropDown.style.ts
  src/components/SharedBundlePage/SharedBundleDropDown/SharedBundleDropDown.tsx
  src/components/SharedBundlePage/SharedBundleDropDown/SharedBundleDropDown.type.ts
  src/components/SharedBundlePage/SharedBundleDropDown/index.ts
  src/utils/copyClip.ts
Labels: 디자인, 기능

#96 [#94] TagFilter 컴포넌트 리펙토링 v1.1.0
  src/components/common/TagFilter/TagFilter.style.tsx
  src/components/common/TagFilter/TagFilter.tsx
Labels: 디자인, 리팩토링

#117 [#116] Button(원형) v.1.0.1
  src/components/common/CircleButton/CircleButton.style.ts
Labels: 디자인, 리팩토링

#98 [#43] 내비게이션 바 v1.0.0
  src/components/common/Navigator/MobileBottomNavBar/MobileBottomNavBar.style.ts
  src/components/common/Navigator/MobileBottomNavBar/MobileBottomNavBar.tsx
  src/components/common/Navigator/MobileBottomNavBar/MobileBottomNavBar.type.ts
  src/components/common/Navigator/MobileTopNavBar/MobileTopNavBar.style.ts
  src/components/common/Navigator/MobileTopNavBar/MobileTopNavBar.tsx
  src/components/common/Navigator/MobileTopNavBar/MobileTopNavBar.type.ts
  src/components/common/Navigator/Navigator.const.ts
  src/components/common/Navigator/Navigator.hook.ts
  src/components/common/Navigator/WebNavBar/WebNavBar.hook.ts
  src/components/common/Navigator/WebNavBar/WebNavBar.style.tsx
  src/components/common/Navigator/WebNavBar/WebNavBar.tsx
  src/components/common/Navigator/WebNavBar/WebNavBar.type.ts
  src/components/common/Navigator/index.ts
Labels: 디자인, 리팩토링

#111 [#93] Toast 알림 구현 v1.0.0
  src/hooks/toast.tsx
  src/routes/index.tsx
Labels: 디자인, 기능

#113 [#112] SharedBundleCard 색상 변경 v1.0.1
  src/components/SharedBundleCard/SharedBundleCard.style.ts
  src/components/SharedBundleCard/SharedBundleCard.tsx
Labels: 디자인

#126 [#125] 프로젝트 세팅 v1.1.4
  README.md
  index.html
  public/favicon.ico
Labels: 세팅

#123 [#118] SharedQuestionBox v1.0.0
  src/components/BundleDropDown/BundleDropDown.style.ts
  src/components/BundleDropDown/BundleDropDown.tsx
  src/components/BundleDropDown/BundleDropDown.type.ts
  src/components/BundleDropDown/index.ts
  src/components/SharedBundle/SharedBundleCard/SharedBundleCard.style.ts
  src/components/SharedBundle/SharedBundleCard/SharedBundleCard.tsx
  src/components/SharedBundle/SharedBundleCard/SharedBundleCard.type.ts
  src/components/SharedBundle/SharedBundleCard/index.ts
  src/components/SharedBundle/SharedBundleDropDown/SharedBundleDropDown.style.ts
  src/components/SharedBundle/SharedBundleDropDown/SharedBundleDropDown.tsx
  src/components/SharedBundle/SharedBundleDropDown/SharedBundleDropDown.type.ts
  src/components/SharedBundle/SharedBundleDropDown/index.ts
  src/components/SharedBundle/SharedQuestionBox/SharedQuestionBox.style.ts
  src/components/SharedBundle/SharedQuestionBox/SharedQuestionBox.tsx
  src/components/SharedBundle/SharedQuestionBox/SharedQuestionBox.type.ts
  src/components/SharedBundle/SharedQuestionBox/index.tsx
  src/components/common/QuestionBox/QuestionBox.style.ts
Labels: 디자인, 기능

#137 [#136] Button v.1.1.0
  src/components/common/Button/Button.tsx
Labels: 기능

#138 [#133] CircleButton v.1.1.0
  src/components/common/CircleButton/CircleButton.style.ts
  src/components/common/CircleButton/CircleButton.tsx
Labels: 기능

#115 [#100] MyBundleItem v1.0.0
  src/components/MyBundle/MyBundleItem/MyBundleItem.style.ts
  src/components/MyBundle/MyBundleItem/MyBundleItem.tsx
  src/components/MyBundle/MyBundleItem/MyBundleItem.type.ts
  src/components/MyBundle/MyBundleItem/index.ts
  src/components/common/QuestionBox/QuestionBox.tsx
  src/hooks/useAccordion.ts
Labels: 🎨디자인🎨, 🛠️기능🛠️

#134 [#131] Textarea 컴포넌트 v1.1.0
  src/components/common/Textarea/Textarea.tsx
Labels: 🐛버그🐛, 📌픽스📌

#139 [#132] Input 컴포넌트 v1.1.1
  src/components/common/Input/Input.tsx
Labels: 🐛버그🐛, 📌픽스📌

#128 [#120] 페이지 - 이용약관 페이지(PolicyPage) 제작
  src/pages/PolicyPage/Policy.const.ts
  src/pages/PolicyPage/Policy.style.ts
  src/pages/PolicyPage/Policy.tsx
Labels: 🎨디자인🎨, 🛠️기능🛠️

#144 [#143] Toggle v.1.2.0
  src/components/common/Toggle/Toggle.style.ts
  src/components/common/Toggle/Toggle.tsx
  src/components/common/Toggle/Toggle.type.ts
Labels: 🎨디자인🎨, 🛠️기능🛠️, 🏃‍♀️신속🏃, 🍜리뷰 3초컷🍜

#156 [#155] Selector 컴포넌트 v1.2.0
  src/components/common/Selector/Selector.style.ts
  src/components/common/Selector/Selector.tsx
  src/components/common/Selector/Selector.type.ts
Labels: 🐛버그🐛, 📌픽스📌, ⚙️리팩토링⚙️, 🏃‍♀️신속🏃, 🍜리뷰 3초컷🍜
